apiVersion: apps/v1
kind: Deployment
metadata:
	name: blackhawk-deployment
	labels:
		app: springboot
spec:
	replicas: 2
	selector:
		matchLabels:
			app: springboot
	template: 
		metadata:
			labels:
				app: springboot
		spec:
			containers:
			- name: springboot
			  image: blackhawk-sboot-01
			  ports:
			  - containerPort: 8080
	
kind: Service
apiVersion: v1
metadata:
  name: blackhawk-service
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 8080
	name: http
			  